addpath(genpath([cd '/b1/']))
addpath(genpath([cd '/parameters/']))
addpath(genpath([cd '/qmt/']))
addpath(genpath([cd '/t1/']))
addpath(genpath([cd '/util/']))
addpath(genpath('/Users/mathieuboudreau/Work/Matlab_Others/niak-0.7.1-ammo'))
addpath(genpath('/Users/mathieuboudreau/Work/mboudrea-phd-code/MATLAB/general'))
